#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=train.intra.res100kb
#SBATCH --account=def-maxwl
#SBATCH --mem=100G
#SBATCH --output=slurm-%j.out
#SBATCH --mail-type=ALL
#SBATCH --mail-user=arab@sfu.ca

module load gcc/5.4.0 hdf5/1.10.1 gmtk/1.4.4

. ../../../segway_posterior_fix/bin/activate

export SEGWAY_NUM_LOCAL_JOBS=32
echo SEGWAY_NUM_LOCAL_JOBS: $SEGWAY_NUM_LOCAL_JOBS

rm -rf TRAINDIR
rm -rf POSTDIR
python -u egpr.py -N 8 --resolution=10 --include-coords=ic.bed --measure-prop-interaction-threshold=1e-06 test.genomedata TRAINDIR test.hic POSTDIR

echo Program finished with exit code $? at: `date`